/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Cdn": {
      "prefixes": {
        "public": string
        "restricted": string
      }
      "publicKeyId": string
      "type": "sst.sst.Linkable"
      "url": string
    }
    "CdnPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CdnPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CdnRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "WebApp": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Zero": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}